**Algorithmics**

You should know how to formulate a problem solution as an algorithm then as a Python program using if, loops (for and while), ....

In [1]:
names=["Ali","Salma",'Rahma']
target_name="Salma"
exist=False
for i in range(0,len(names),1):
  if names[i]==target_name:
    exist=True
    break

In [2]:
exit

**Data structures**

In Python, we should know data strcutures that represent collections, arrays, ...

The main data structures are lists and dictionaries

Lists

In [ ]:
names=[]

In [ ]:
names.append('Salah')

In [ ]:
names

['Salah']

In [ ]:
names[0]

'Salah'

Dictionaries

In [1]:
names=['Salah','Ahmed','Sonia']
notes=[12.5,15.7,17.75]

In [2]:
notes={'Salah':12.5,'Ahmed':15.7,'Sonia':17.75}

In [3]:
notes['Sonia']

17.75

**Object Oriented Programming (OOP)**

Object Oriented Programming means that you define a problem entities as classes.

You should know how to define a Python class

In [4]:
class Point:
  def __init__(self,name, x, y): # class contructor
    # self.name , self.x and self.y are attributes
    self.name=name
    self.x=x
    self.y=y
  def show(self):
    print('%s[%.2f,%.2f]' % (self.name, self.x, self.y))

In [5]:
p1=Point('p1',5,2)
p1.show()

p1[5.00,2.00]


**Functional Programming**

In order to optimize time cost and reduce code lines, useful routines are proposed :
- map : a function that allows to transform a list into  another list of the same size
- filter : a function that allows to filter a list elements
- reduce : a function that allows to compute a value from a data strcture, like sum of array elements

In [6]:
names=['ali','sonia','rahma']
names_upper=[]
for i in range(len(names)):
  names_upper.append(names[i].upper())

In [7]:
names_upper

['ALI', 'SONIA', 'RAHMA']

In [9]:
def convert_upper(name):
  return name.upper()
list(map(convert_upper, names))

['ALI', 'SONIA', 'RAHMA']

In [1]:
convert_upper= lambda name: name.upper()

In [11]:
list(map(convert_upper, names))

['ALI', 'SONIA', 'RAHMA']

In [12]:
list(map(lambda name: name.upper(), names))

['ALI', 'SONIA', 'RAHMA']

**Math Programming**

It is import to represent numerical data (vectors, matrices, ...) in programs.

Python allow to represent such math objects as numpy arrays

Vectors

In [ ]:
x=[1,2,3]
y=[2,2,2]
z=x+y
z

[1, 2, 3, 2, 2, 2]

In [13]:
import numpy as np
x=np.array([1,2,3]) # vector
y=np.array([2,2,2]) # vector
z=x+y
z # vector

array([3, 4, 5])

Matrices

In [15]:
X=np.array([[30,1200.5],[25,1500.75],[45,2100.87]])
X

array([[  30.  , 1200.5 ],
       [  25.  , 1500.75],
       [  45.  , 2100.87]])

In [19]:
means=np.mean(X, axis=0)
means

array([  33.33333333, 1600.70666667])

**Data Programming**

It is important to represent tabular data (Excel sheets, DB tables, ...) in Python program.

Python allow to represent such data structures as pandas dataframes

In [22]:
import pandas as pd

df=pd.DataFrame(X , columns=['age','salary'], index=['Ali','Salma','Rahma'])
df

age   salary
Ali    30.0  1200.50
Salma  25.0  1500.75
Rahma  45.0  2100.87

In [23]:
df['salary']

Ali      1200.50
Salma    1500.75
Rahma    2100.87
Name: salary, dtype: float64

In [24]:
df['high_salary']=df['salary'].apply(lambda salary : salary>2000)
df

age   salary  high_salary
Ali    30.0  1200.50        False
Salma  25.0  1500.75        False
Rahma  45.0  2100.87         True